#!/usr/bin/env bash
# Správa přístupových klíčů Lumenu (nainstaluje ho update.sh):
#   sudo lumen-keys add "Honza"             klíč pro 1 zařízení
#   sudo lumen-keys add "Honza" --devices 2
#   sudo lumen-keys list
#   sudo lumen-keys reset 2                 uvolní zařízení klíče č. 2
#   sudo lumen-keys revoke 2                zruší klíč č. 2
[[ $EUID -eq 0 ]] || exec sudo "$0" "$@"
cd @APP_DIR@
exec sudo -u lumen env DATA_DIR=/var/lib/lumen PYTHONDONTWRITEBYTECODE=1 @APP_DIR@/.venv/bin/python keys.py "$@"
